### ISSUE TITLE
Complete requirements for site launch (from kupo site launch checklist)

### ISSUE THREAD

**Issue by lmammino** [FullStackBulletin/fullstackbulletin.com#18]
[Kupo site launch checklist](https://github.com/phanan/kupo)

- [ ] `<html> tag should have an explicit lang attribute` (#22)
- [ ] `Favicon not found at https://fullstackbulletin.com/favicon.ico` (#14)
- [ ] `App icons for mobile devices not found`
- [ ] `At least one of og:url, og:title, og:description, and og:image meta properties is missing` (#10)
- [ ] `At least one of twitter:card, twitter:title, twitter:description, and twitter:image meta properties is missing` (#10)
